### ISSUE TITLE
Can't install on bitbucket pipeline (work with 0.10.2, not with 0.10.14)

### ISSUE THREAD

**Issue by ghost** [os97673/debase-ruby_core_source#26]
I have an issue with the latest version of this gem when the Bitbucket pipeline starts the build, no problem in a local environment.
I attach the output of the `bundle install` from the pipeline (with version 0.10.14).

[pipelineLog-148.txt](https://github.com/os97673/debase-ruby_core_source/files/7863125/pipelineLog-148.txt)

```
Errno::ENOENT: No such file or directory @ apply2files - /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.6.0/gems/debase-ruby_core_source-0.10.14/lib/debase/ruby_core_source/ruby-2.0.0-p353/insns_info.inc
  /usr/local/lib/ruby/2.6.0/fileutils.rb:1321:in `chmod'
  /usr/local/lib/ruby/2.6.0/fileutils.rb:1321:in `chmod'
  /usr/local/lib/ruby/2.6.0/fileutils.rb:997:in `block in chmod'
  /usr/local/lib/ruby/2.6.0/fileutils.rb:996:in `each'
  /usr/local/lib/ruby/2.6.0/fileutils.rb:996:in `chmod'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:410:in `block (3 levels) in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:408:in `open'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:408:in `block (2 levels) in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:389:in `block in extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:522:in `block in open_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:519:in `wrap'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:519:in `open_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:388:in `extract_tar_gz'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:368:in `block (2 levels) in extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:365:in `block in extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `open'
  /usr/local/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /usr/local/lib/ruby/2.6.0/rubygems/package.rb:362:in `extract_files'
  /usr/local/lib/ruby/2.6.0/rubygems/installer.rb:851:in `extract_files'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:204:in `install'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in `loop'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

**Comment by Marychoffel22** [comment]
Assigned
